### ISSUE TITLE
资源缺失

### ISSUE THREAD

**Issue by WeaponMaster** [large-scale-recsys-in-action/large-scale-recsys-in-action#1]
随书的代码能看到,但是没找到数据,能上传一下数据吗?

**Comment by large-scale-recsys-in-action** [comment]
> 随书的代码能看到,但是没找到数据,能上传一下数据吗?
[第 9 章的数据代码](https://github.com/large-scale-recsys-in-action/large-scale-recsys-in-action/blob/main/chapter%209/spark/data.py)可以直接生成数据样例，如果你没有环境，我也上传了生成后的数据在[第 9 章 spark 目录下](https://github.com/large-scale-recsys-in-action/large-scale-recsys-in-action/tree/main/chapter%209/spark/dataset)
